name:                modular
version:             0.1.0.0
github:              "pgujjula/modular"
license:             BSD3
author:              "Preetham Gujjula"
maintainer:          "preetham.gujjula@gmail.com"
copyright:           "2018 Preetham Gujjula"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Type-safe modular arithmetic, with modulus specifiable at runtime or compile time.
category: Math
description: Please the module documentation for Numeric.Modular.

dependencies:
  - base >= 4.7 && < 5
  - ghc-typelits-knownnat >= 0.5 && < 1

ghc-options: -Wall -Werror

library:
  source-dirs: src
  exposed-modules:
    - Numeric.Modular
