name:                modular
version:             0.1.0.7
github:              "pgujjula/modular"
license:             BSD3
author:              "Preetham Gujjula"
maintainer:          "preetham.gujjula@gmail.com"
copyright:           "2018 Preetham Gujjula"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Type-safe modular arithmetic
category: Math
description: ! "Please see the GitHub page at
    <https://github.com/pgujjula/modular> for installation instructions, and
    the module documentation for Numeric.Modular for usage instructions."

dependencies:
  - base >= 4.7 && < 5
  - ghc-typelits-knownnat >= 0.5 && < 1

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Numeric.Modular
